[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m streamlit run cannae_dashboard.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
PYTHON_VERSION = "3.11.0"
